/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content */
        get: operations["get_content_api_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Guest */
        post: operations["new_guest_api_guest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["sessions_api_sessions_get"];
        put?: never;
        /** Create */
        post: operations["create_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__identifier__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_sessions__identifier__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{identifier}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect */
        post: operations["connect_api_sessions__identifier__connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{identifier}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Command */
        post: operations["apply_command_api_sessions__identifier__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{identifier}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat */
        post: operations["heartbeat_api_sessions__identifier__heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{identifier}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_sessions__identifier__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{identifier}/playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Playback */
        post: operations["playback_api_sessions__identifier__playback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/{purpose_id}/playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Expression Playback */
        post: operations["expression_playback_api_content__purpose_id__playback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /** Id */
            id: string;
            /** Input Id */
            input_id: string;
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /** Question Id */
            question_id: string;
            transcript: components["schemas"]["Transcript"];
            /** Capture Seconds */
            capture_seconds: number;
            /**
             * Capture Limited
             * @default false
             */
            capture_limited: boolean;
        };
        /** Assessment */
        Assessment: {
            /**
             * Status
             * @default none
             * @enum {string}
             */
            status: "none" | "pending" | "running" | "ready" | "unavailable";
            /** Request Id */
            request_id: string | null;
            /** Attempt Id */
            attempt_id: string | null;
            /** Frozen Hash */
            frozen_hash: string | null;
            /** Deadline */
            deadline: number | null;
            result: components["schemas"]["AssessmentResult"] | null;
            /** Error */
            error: string | null;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Prompt Version
             * @default assessment-v1
             */
            prompt_version: string;
            /**
             * Rubric Version
             * @default wording-v1
             */
            rubric_version: string;
        };
        /** AssessmentResult */
        AssessmentResult: {
            dimensions: components["schemas"]["Dimensions"];
            /** Strengths */
            strengths: components["schemas"]["Note"][];
            /** Issues */
            issues: components["schemas"]["Note"][];
            retry_priority: components["schemas"]["Priority"];
            /** Spoken Summary */
            spoken_summary: string;
            /** Modeled Example */
            modeled_example: string;
            /** Takeaway */
            takeaway: string;
        };
        /** CoachingReply */
        CoachingReply: {
            /** Text */
            text: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** CoachingTurn */
        CoachingTurn: {
            /** Id */
            id: string;
            /** Input Id */
            input_id: string;
            transcript: components["schemas"]["Transcript"];
            reply: components["schemas"]["CoachingReply"];
            /** Message Id */
            message_id: string;
        };
        /** Command */
        "Command-Input": {
            /** Command Id */
            command_id: string;
            /** Expected Revision */
            expected_revision: number;
            /** Connection Epoch */
            connection_epoch?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "pause" | "finish" | "done" | "use_answer" | "try_again" | "retry_operation" | "mute" | "unmute" | "replay" | "continue_answer" | "hint" | "focused_retry" | "expression";
            /** Input Id */
            input_id?: string | null;
            /** Expression Id */
            expression_id?: ("expression" | "alternative" | "example") | null;
            /** Target Note Id */
            target_note_id?: string | null;
        };
        /** Command */
        "Command-Output": {
            /** Command Id */
            command_id: string;
            /** Expected Revision */
            expected_revision: number;
            /** Connection Epoch */
            connection_epoch: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "pause" | "finish" | "done" | "use_answer" | "try_again" | "retry_operation" | "mute" | "unmute" | "replay" | "continue_answer" | "hint" | "focused_retry" | "expression";
            /** Input Id */
            input_id: string | null;
            /** Expression Id */
            expression_id: ("expression" | "alternative" | "example") | null;
            /** Target Note Id */
            target_note_id: string | null;
        };
        /** ConnectResult */
        ConnectResult: {
            session: components["schemas"]["Session"];
            /** Url */
            url: string;
            /** Token */
            token: string;
        };
        /** Content */
        Content: {
            /** Version */
            version: string;
            /** Purposes */
            purposes: components["schemas"]["Purpose"][];
            /** Rubric */
            rubric: {
                [key: string]: string[];
            };
        };
        /** CreateSession */
        CreateSession: {
            /** Purpose Id */
            purpose_id: string;
            /** Command Id */
            command_id: string;
            /** Source Session Id */
            source_session_id?: string | null;
        };
        /** Dimension */
        Dimension: {
            /**
             * Status
             * @enum {string}
             */
            status: "scored" | "not_enough_detail" | "transcript_unclear" | "assessment_unavailable";
            /** Score */
            score: number | null;
            /**
             * Basis
             * @constant
             */
            basis: "wording";
            /** Explanation */
            explanation: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** Dimensions */
        Dimensions: {
            naturalness: components["schemas"]["Dimension"];
            workplace_tone: components["schemas"]["Dimension"];
        };
        /** Evidence */
        Evidence: {
            /**
             * Turn Id
             * @description Copy an accepted_answers[].id exactly.
             */
            turn_id: string;
            /**
             * Answer Revision
             * @description Copy the revision of that accepted answer.
             */
            answer_revision: number;
            /** Observation */
            observation: string;
            /** Quote */
            quote: string | null;
        };
        /** ExpressionPlayback */
        ExpressionPlayback: {
            /**
             * Expression Id
             * @enum {string}
             */
            expression_id: "expression" | "alternative" | "example";
        };
        /** FocusedRetry */
        FocusedRetry: {
            /** Id */
            id: string;
            /** Target Note Id */
            target_note_id: string;
            /** Target */
            target: string;
            /** Situation */
            situation: string | null;
            /** Setup */
            setup: string | null;
            /** Question Id */
            question_id: string | null;
            /** Answers */
            answers: components["schemas"]["Answer"][];
            assessment: components["schemas"]["TargetedAssessment"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Heartbeat */
        Heartbeat: {
            /** Connection Epoch */
            connection_epoch: string;
        };
        /** Helper */
        Helper: {
            /** Id */
            id: string;
            /** Generation Id */
            generation_id: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "running" | "ready" | "unavailable";
            /** Text */
            text: string | null;
            /** Deadline */
            deadline: number | null;
        };
        /** Input */
        Input: {
            /** Id */
            id: string;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "sealing" | "awaiting_limit_confirmation" | "submitting";
            /** First Speech At */
            first_speech_at: number | null;
            /**
             * Cue Shown
             * @default false
             */
            cue_shown: boolean;
            /**
             * Capture Seconds
             * @default 0
             */
            capture_seconds: number;
            /**
             * Capture Limited
             * @default false
             */
            capture_limited: boolean;
            /** Continuation Of */
            continuation_of: string | null;
            /**
             * Max Capture Seconds
             * @default 120
             */
            max_capture_seconds: number;
        };
        /** Note */
        Note: {
            /**
             * Id
             * @description Unique note key, such as note_1. This is not an answer ID.
             */
            id: string;
            /** Observation */
            observation: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Suggestion */
            suggestion: string;
            /** Example */
            example: string;
            /** Reason */
            reason: string;
        };
        /** Playback */
        Playback: {
            /** Message Id */
            message_id: string;
        };
        /** Priority */
        Priority: {
            /**
             * Note Id
             * @description Copy the id of a Note returned in strengths or issues, not an answer ID.
             */
            note_id: string;
            /** Suggestion */
            suggestion: string;
        };
        /** Purpose */
        Purpose: {
            /** Purpose Id */
            purpose_id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Order */
            order: number;
            /** Title */
            title: string;
            /** Expression */
            expression: string;
            /** Alternative */
            alternative: string;
            /** Explanation */
            explanation: string;
            /** Example */
            example: string;
            /** Hint Starter */
            hint_starter: string;
            /** Preset Situation */
            preset_situation: string;
            /** Learner Role */
            learner_role: string;
            /** Tutor Role */
            tutor_role: string;
            /** Communication Goal */
            communication_goal: string;
            /** Opening Direction */
            opening_direction: string;
            /**
             * Difficulty
             * @default B1-B2
             */
            difficulty: string;
            /** Allowed Variations */
            allowed_variations: string[];
            /**
             * Integrated
             * @default false
             */
            integrated: boolean;
        };
        /** Receipt */
        Receipt: {
            /** Command Id */
            command_id: string;
            /** Revision */
            revision: number;
            /** Input Id */
            input_id: string | null;
            /** Answer Id */
            answer_id: string | null;
        };
        /** Session */
        Session: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Id */
            id: string;
            /** Guest Id */
            guest_id: string;
            /** Purpose Id */
            purpose_id: string;
            /** Content Version */
            content_version: string;
            /** Conversation Model */
            conversation_model: string;
            /**
             * Prompt Version
             * @default conversation-v1
             */
            prompt_version: string;
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /**
             * Sequence
             * @default 1
             */
            sequence: number;
            /**
             * Lifecycle
             * @default paused
             * @enum {string}
             */
            lifecycle: "in_progress" | "paused" | "completed";
            /**
             * Phase
             * @default roleplay
             * @enum {string}
             */
            phase: "roleplay" | "coaching" | "retry";
            /**
             * Substate
             * @default connecting
             * @enum {string}
             */
            substate: "connecting" | "opening" | "listening" | "thinking" | "speaking" | "capped" | "assessment_pending" | "ready" | "unavailable";
            /** Created At */
            created_at: number;
            /** Last Practice At */
            last_practice_at: number;
            /** Expires At */
            expires_at: number;
            /** Completed At */
            completed_at: number | null;
            /** Connection Epoch */
            connection_epoch: string | null;
            /** Room */
            room: string | null;
            /** Participant */
            participant: string | null;
            /** Generation Id */
            generation_id: string;
            /** Situation */
            situation: string | null;
            /** Setup */
            setup: string | null;
            /** Question Id */
            question_id: string | null;
            /** Answers */
            answers: components["schemas"]["Answer"][];
            /** Messages */
            messages: components["schemas"]["TutorMessage"][];
            input: components["schemas"]["Input"] | null;
            pending_command: components["schemas"]["Command-Output"] | null;
            /** Receipts */
            receipts: {
                [key: string]: components["schemas"]["Receipt"];
            };
            assessment: components["schemas"]["Assessment"];
            /** Notice */
            notice: string | null;
            /**
             * Capture Muted
             * @default false
             */
            capture_muted: boolean;
            /**
             * Replay Restore Capture
             * @default false
             */
            replay_restore_capture: boolean;
            helper: components["schemas"]["Helper"] | null;
            /** Retries */
            retries: components["schemas"]["FocusedRetry"][];
            /** Coaching Turns */
            coaching_turns: components["schemas"]["CoachingTurn"][];
            /** Source Session Id */
            source_session_id: string | null;
            /** Previous Opening */
            previous_opening: string | null;
        };
        /** TargetedAssessment */
        TargetedAssessment: {
            /**
             * Status
             * @default none
             * @enum {string}
             */
            status: "none" | "pending" | "running" | "ready" | "unavailable";
            /** Request Id */
            request_id: string | null;
            /** Attempt Id */
            attempt_id: string | null;
            /** Frozen Hash */
            frozen_hash: string | null;
            /** Deadline */
            deadline: number | null;
            result: components["schemas"]["TargetedResult"] | null;
        };
        /** TargetedResult */
        TargetedResult: {
            /** Target Note Id */
            target_note_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "demonstrated" | "developing" | "not_enough_detail" | "transcript_unclear";
            /** Observation */
            observation: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Suggestion */
            suggestion: string;
            /** Modeled Example */
            modeled_example: string;
        };
        /** Transcript */
        Transcript: {
            /** Text */
            text: string;
            /**
             * Status
             * @default reliable
             * @enum {string}
             */
            status: "reliable" | "unclear";
            /** Segment Ids */
            segment_ids: string[];
            /** Source Identity */
            source_identity: string;
        };
        /** TutorMessage */
        TutorMessage: {
            /** Id */
            id: string;
            /** Generation Id */
            generation_id: string;
            /** Text */
            text: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "opening" | "follow_up" | "bridge" | "coaching" | "help" | "coaching_answer" | "retry_coaching";
            /**
             * Delivery
             * @default pending
             * @enum {string}
             */
            delivery: "pending" | "playing" | "completed" | "interrupted" | "failed";
            /** Playback Id */
            playback_id: string | null;
            /** Played Text */
            played_text: string | null;
            /**
             * Superseded
             * @default false
             */
            superseded: boolean;
            /** Retry Id */
            retry_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_content_api_content_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Content"];
                };
            };
        };
    };
    new_guest_api_guest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    create_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_sessions__identifier__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_api_sessions__identifier__connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_command_api_sessions__identifier__commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_api_sessions__identifier__heartbeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Heartbeat"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_sessions__identifier__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    playback_api_sessions__identifier__playback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Playback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expression_playback_api_content__purpose_id__playback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purpose_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpressionPlayback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
